http:
  port: "8081"
  
sfdc:
  username: "debojitchow@njclabs.com"
  password: "Debojit@98"
  token: 
  
file:
  accountsDie:"C:\Users\HP\Desktop\DevFnd\APDevFundamentals4.3_studentFiles_29apr2021\APDevFundamentals4.3_studentFiles_29apr2021\resources"
  
db:
  host: "iltdb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"