http:
  port: "8081"
  
american:
  host: "http://training-american-flights-dc-proxy.us-e2.cloudhub.io/flights"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "69e6fc9196af41809692fa486f3df1c1"
  client_secret: "3c03D102eDb5471C89F643A0c4a0720C"
  
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"